language: php

sudo: required

php:
 - '7.1'

services:
 - docker
 
before_install: composer global require fxp/composer-asset-plugin -vvv

 
install:
 - composer self-update
 - composer install

script:
 - composer test
 - php .scripts/translations.php somenergia_translations
 - php .scripts/translations.php somenergia-theme
 - php .scripts/translations.php somenergia_calendar
 - php .scripts/translations.php somenergia_drive
 - php .scripts/translations.php somenergia_index
 - php .scripts/translations.php somenergia-customization
 - php .scripts/translations.php rm_group_autosubscription